version: '3.7'

services:
  backend:
    build:
      context: .
      target: 'develop'
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      - RUST_LOG=actix_web=debug
      - TZ=Asia/Tokyo
      - PORT=8088
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: bash -c "diesel setup && cargo watch -x run"
    tty: true
  db:
    build:
      context: .
      target: 'db'
    ports:
      - "5432:5432"
    volumes:
      - pgdate:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      TZ: Asia/Tokyo
    restart: always

volumes:
  cargo-cache:
  target-cache:
  pgdate: